// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// tkmeans_lowmem
arma::mat tkmeans_lowmem(arma::mat& M, int n_cluster, double alpha, int nstart, int iter, double tol);
RcppExport SEXP tkmeans_tkmeans_lowmem(SEXP MSEXP, SEXP n_clusterSEXP, SEXP alphaSEXP, SEXP nstartSEXP, SEXP iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type n_cluster(n_clusterSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type nstart(nstartSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    __result = Rcpp::wrap(tkmeans_lowmem(M, n_cluster, alpha, nstart, iter, tol));
    return __result;
END_RCPP
}
// scale_lowmem
arma::mat scale_lowmem(arma::mat& M);
RcppExport SEXP tkmeans_scale_lowmem(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    __result = Rcpp::wrap(scale_lowmem(M));
    return __result;
END_RCPP
}
// BIC_lowmem
double BIC_lowmem(arma::mat& data, arma::mat& centres);
RcppExport SEXP tkmeans_BIC_lowmem(SEXP dataSEXP, SEXP centresSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type centres(centresSEXP);
    __result = Rcpp::wrap(BIC_lowmem(data, centres));
    return __result;
END_RCPP
}
// tmeansClust_lowmem
arma::uvec tmeansClust_lowmem(arma::mat& data, arma::mat& centres);
RcppExport SEXP tkmeans_tmeansClust_lowmem(SEXP dataSEXP, SEXP centresSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type centres(centresSEXP);
    __result = Rcpp::wrap(tmeansClust_lowmem(data, centres));
    return __result;
END_RCPP
}
