# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib tkmeans
NULL

#'Performs trimmed k-means clustering algorithm on a matrix of data. Each row is an observation.
#'
#'@param M matrix of data to be clustered
#'@param n_cluster number of clusters
#'@param alpha proportion of data to be trimmed
#'@param nstart number of restarts
#'@param iter maximum number of iterations
#'@param tol convergence criteria
#'@return matrix of cluster centres
#'@export
tkmeans_lowmem <- function(M, n_cluster, alpha, nstart, iter, tol) {
    .Call('tkmeans_tkmeans_lowmem', PACKAGE = 'tkmeans', M, n_cluster, alpha, nstart, iter, tol)
}

#'Recales each row to have mean 0 and sd 1.
#'
#'@param M matrix of data
#'@return first row mean shifts, second row sd so that scaling can be undone. Scales original matrix in place
#'@export
scale_lowmem <- function(M) {
    .Call('tkmeans_scale_lowmem', PACKAGE = 'tkmeans', M)
}

#'Calculates BIC for a given clustering.
#'
#'@param data matrix of data
#'@param centres matrix of cluster means
#'@return BIC value
#'@export
BIC_lowmem <- function(data, centres) {
    .Call('tkmeans_BIC_lowmem', PACKAGE = 'tkmeans', data, centres)
}

#'Allocates each Row (observation) in data to the nearest cluster centre.
#'
#'@param data matrix of data to be clustered
#'@param centres set of cluster means
#'@return vector of cluster allocations
#'@export
tmeansClust_lowmem <- function(data, centres) {
    .Call('tkmeans_tmeansClust_lowmem', PACKAGE = 'tkmeans', data, centres)
}

