# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mahalanobis <- function(x, center, cov) {
    .Call('tkmeans_Mahalanobis', PACKAGE = 'tkmeans', x, center, cov)
}

dmvnorm_arma <- function(x, mean, sigma, log = FALSE) {
    .Call('tkmeans_dmvnorm_arma', PACKAGE = 'tkmeans', x, mean, sigma, log)
}

distCentre <- function(n_cluster, ui, centres, lambda, d) {
    .Call('tkmeans_distCentre', PACKAGE = 'tkmeans', n_cluster, ui, centres, lambda, d)
}

distCentre2 <- function(n_cluster, ui, centres, lambda, d) {
    .Call('tkmeans_distCentre2', PACKAGE = 'tkmeans', n_cluster, ui, centres, lambda, d)
}

distCentre3 <- function(n_cluster, ui, centres, lambda, d) {
    .Call('tkmeans_distCentre3', PACKAGE = 'tkmeans', n_cluster, ui, centres, lambda, d)
}

max_index <- function(x) {
    .Call('tkmeans_max_index', PACKAGE = 'tkmeans', x)
}

min_index <- function(x) {
    .Call('tkmeans_min_index', PACKAGE = 'tkmeans', x)
}

init_centres <- function(M, n_cluster) {
    .Call('tkmeans_init_centres', PACKAGE = 'tkmeans', M, n_cluster)
}

tkmeans_lowmem <- function(M, n_cluster, alpha, nstart, iter) {
    .Call('tkmeans_tkmeans_lowmem', PACKAGE = 'tkmeans', M, n_cluster, alpha, nstart, iter)
}

scale_lowmem <- function(M) {
    .Call('tkmeans_scale_lowmem', PACKAGE = 'tkmeans', M)
}

BIC_lowmem <- function(centres, data) {
    .Call('tkmeans_BIC_lowmem', PACKAGE = 'tkmeans', centres, data)
}

tmeansClust_lowmem <- function(data, centres) {
    .Call('tkmeans_tmeansClust_lowmem', PACKAGE = 'tkmeans', data, centres)
}

